import SideBar from "@/components/SideBar";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" bg-gray-300 flex min-h-screen m-4 gap-4">
        <SideBar />
        <div className=" w-screen h-[100%]">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
